apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ott
  template:
    metadata:
      labels:
        app: ott
    spec:
      containers:
      - image: okteto.dev/ott:latest
        name: ott
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "10a08354-bc8a-42ff-8b1f-346f900133f2"
        - name: Vless_Path
          value: "/app"
        - name: Vmess_UUID
          value: "10a08354-bc8a-42ff-8b1f-346f900133f2"
        - name: Vmess_Path
          value: "/add"
        - name: Share_Path
          value: "$Share_Path"
